[package]
name = "jq-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version="4.5.19", features=["derive"] }
indexmap = "2.6.0"
serde = "1.0.210"
serde_json = { version = "1.0.128", features = ["preserve_order"] }
thiserror = "1.0.64"
